### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by inverse** [milin/giticket#10]
Why not tag a release to make discovery a bit nicer?

**Comment by milind-shakya-sp** [comment]
@inverse do you mean a github release?

**Comment by inverse** [comment]
@milind-shakya-sp Sorry my previous message was a bit short.

Correct me if I am wrong - so to use this right now we need to use the latest git hash? I was just thinking perhaps using a git tag would provide a nicer versioning schema. Especially if they follow semantic versioning and things change.

**Comment by milind-shakya-sp** [comment]
@inverse you're right. finally had some time to draft a release. https://github.com/milin/giticket/releases/tag/v1.0

**Comment by inverse** [comment]
Thanks so much :) much appreciated!
