### ISSUE TITLE
Update is only bailed if ticket is in first line

### ISSUE THREAD

**Issue by t4n0** [milin/giticket#22]
Hi,

first of all: Thank you for your work here. Love it.

Unfortunately the bail does not work for our use case. We add the ticket not in the first line but are required to add it to the body of the commit message. In that case the early return you provided does not work and the ticket is added twice (e.g. when amending an exisiting commit).

I forked your repo and changed it to our needs: https://github.com/t4n0/giticket/commit/8f4ff1987d7de93dd58171373f8e5153b45e9fd7

Is this something you would consider fixing upstream, too? If so let me know.

Thanks

**Comment by milind-shakya-sp** [comment]
Yes, please consider opening a pull request with your changes. Happy to review it and merge it if applicable, when i get sometime this week.
